# Generated by Django 5.2 on 2025-04-18 12:34

import prime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="telefone",
        ),
        migrations.AddField(
            model_name="cliente",
            name="cep",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="complemento",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                unique=True,
                validators=[prime.models.validate_cpf],
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="estado",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="historico_pedidos",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="numero",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="rg",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefone1",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[prime.models.validate_telefone],
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefone2",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[prime.models.validate_telefone],
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
