# Generated by Django 5.2 on 2025-04-21 13:16

import django.db.models.deletion
import prime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0002_remove_cliente_telefone_cliente_cep_cliente_cidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cep",
            field=models.CharField(default="00000-000", max_length=9),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(default="Desconhecida", max_length=100),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="complemento",
            field=models.CharField(default="Nenhum", max_length=100),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(
                blank=True,
                default="000.000.000-00",
                max_length=14,
                unique=True,
                validators=[prime.models.validate_cpf],
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="data_nascimento",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.CharField(default="Não informado", max_length=255),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="estado",
            field=models.CharField(default="XX", max_length=2),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="historico_pedidos",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="numero",
            field=models.CharField(default="S/N", max_length=10),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="rg",
            field=models.CharField(default="000000000", max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone1",
            field=models.CharField(blank=True, default="Não informado", max_length=15),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone2",
            field=models.CharField(blank=True, default="Não informado", max_length=15),
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_pedido", models.DateField()),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="prime.cliente"
                    ),
                ),
            ],
        ),
    ]
