# Generated by Django 5.2 on 2025-04-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0003_alter_cliente_cep_alter_cliente_cidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
