# Generated by Django 5.2 on 2025-04-26 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0004_alter_pedido_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("dinheiro", "Dinheiro"),
                    ("cartao", "Cartão"),
                    ("pix", "Pix"),
                ],
                default="dinheiro",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="prime.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("quantidade", models.PositiveIntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="prime.pedido",
                    ),
                ),
            ],
        ),
    ]
