# Generated by Django 5.2 on 2025-05-04 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0005_pedido_forma_pagamento_alter_pedido_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="parcelas",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="prime.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
