# Generated by Django 5.2 on 2025-05-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0006_pedido_parcelas_alter_pedido_cliente_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itempedido",
            old_name="preco",
            new_name="valor_unitario",
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="quantidade",
            field=models.IntegerField(),
        ),
    ]
