# Generated by Django 5.2 on 2025-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0007_rename_preco_itempedido_valor_unitario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
