# Generated by Django 5.2 on 2025-05-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0008_alter_pedido_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="acrescimo",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="desconto",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pedido",
            name="valor_parcela",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
