# Generated by Django 5.2 on 2025-05-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0009_pedido_acrescimo_pedido_desconto_pedido_subtotal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pix", "Pix"),
                    ("dinheiro", "Dinheiro"),
                    ("debito", "Cartão de Débito"),
                    ("credito", "Cartão de Crédito"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
