# Generated by Django 5.1.7 on 2025-05-14 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0010_alter_pedido_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
