# Generated by Django 5.1.7 on 2025-05-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0011_pedido_data_entrega_alter_cliente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_fechado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='situacao',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='nao_iniciado', max_length=20),
        ),
    ]
