# Generated by Django 5.2.6 on 2026-04-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0012_pedido_pedido_fechado_pedido_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
