# Generated by Django 5.2.6 on 2025-10-01 00:45

import prime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0012_pedido_pedido_fechado_pedido_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone1',
            field=models.CharField(blank=True, default='Não informado', max_length=15, validators=[prime.models.validate_telefone]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone2',
            field=models.CharField(blank=True, default='Não informado', max_length=15, validators=[prime.models.validate_telefone]),
        ),
    ]
